test: &default

  # Credentials for REST APIs
  client_id: AUsrPnX5Y1RbCx9wai5fvoMMAC-DwveTEv6m-_u_vOuHGLxbkTz0vU-_oiAwzTnFkwP0_CfGAfN3p5hS
  client_secret: ENBTnrNmbpFzlQOsEKpaIVtq7i0fNkpgYC7WE0FU4Imhv_8kz2UA7hWgUhbn8bt5r3RKIeLzCqm-Mu6B

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
